### ISSUE TITLE
SystemDllNotFoundException on SDK

### ISSUE THREAD

**Issue by EricBatlle** [ceptontech/cepton_sdk_redist#13]
Hi, using the last sample with C# SDK is throwing this error on line 342:

`System.DllNotFoundException: 'Unable to load DLL 'cepton_sdk.dll': The specified module could not be found.
`
Seems like the DllImport has a wrong entryPoint called "cepton_sdk_create_options". Could be?

Thanks!

**Comment by liaody** [comment]
Hi Eric, Can you check that your C# app is compiled to 64bit? Our cepton_sdk.dll is 64bit only.

**Comment by EricBatlle** [comment]
Wasn't that, the SDK requires the new Redistributable package
