### ISSUE TITLE
New feature request : Export pcap data frames to bin format 

### ISSUE THREAD

**Issue by jadhavhninad** [ceptontech/cepton_sdk_redist#3]
Currently the python cepton_exporter support only limited format.

cepton_export.py: error: argument --format: invalid choice: 'BIN' (choose from 'CSV', 'LAS', 'PCD', 'PLY')

 Is it possible to add support for exporting to bin files?

Thanks.

**Comment by hjiang36** [comment]
Hi Ninad,

Bin files are for compressed binary format and does not have universal definition.
If you have certain specific format in mind, please let us know.

Thanks

**Comment by jadhavhninad** [comment]
Hi Jiang,
Thanks for your reply. I was testing the KITTI dataset before (http://www.cvlibs.net/datasets/kitti/raw_data.php) and the raw data files in that have compatibility with an opensource lidar dataset annotator that I found and will be using for my project. These have a .bin extension, so I am quite not sure of what the format is.  The file type is : Binary (application/octet-stream). Let me know if this helps.

Thanks,
Ninad

**Comment by spectralflight** [comment]
Hi Ninad,

It sounds like they are just storing an array of floats (X, Y, Z), but it isn't super clear from the documentation. If you look at the cepton_sdk_redist/python/cepton_sdk/export.py (save_points_pcd, line 113), you can copy and paste this code and use it to export to arbitrary binary formats. The PCD format is a text header + array of floats. Does your annotator not accept LAS file format?

Best,
Jon

**Comment by hjiang36** [comment]
Hi Ninad,

The point cloud data in KITTI data set is stored as X, Y, Z and intensity for each point and the data file is just a compact representation of these floats (see section III A. part (c) in their doc: https://www.mrt.kit.edu/z/publ/download/2013/GeigerAl2013IJRR.pdf). Note that the coordinate system of KITTI is different from the definition in cepton_sdk. It should be straightforward to convert from one to another.

As Jon mentioned, you can customize export.py to write out the bin file.

**Comment by jadhavhninad** [comment]
Thanks Jiang and Jon. I updated the export.py to store the point cloud in the same format as KITTI and now can read it via the annotator. 
How do I find the details of the cepton_sdk coordinate system?

**Comment by hjiang36** [comment]
cepton_sdk uses positive x to the right, positive y to the front and positive z to the up direction.

**Comment by jadhavhninad** [comment]
Thanks Jiang. I have some more questions regarding the default frame size. Should I open a new issue or post it in this thread?

**Comment by hjiang36** [comment]
Feel free to open a new one and close this one.
Thanks
