### ISSUE TITLE
Changing default frame size to get a more denser point cloud

### ISSUE THREAD

**Issue by jadhavhninad** [ceptontech/cepton_sdk_redist#4]
Hi,
After extracting individual frames, I notices that per frame about ~6000 points are extracted per frame. Is there a way to change the density of the cloud?

Thanks,
Ninad

**Comment by hjiang36** [comment]
The density of the point cloud mostly depends on the sensor model you are using.
Can you let us know the sensor model and the frame duration? Is 6000 points the valid points or the total points?

Thanks
Haomiao Jiang

**Comment by jadhavhninad** [comment]
Hi Jiang,
The current pcap file that we have is from HR80W and after checking the spec sheet I saw that the device streams at 10Hz per sec and the total points per sec are about 100000. So to get frame per second, I had to merge the individual frames generated in 1 second . Let me know if there is a better approach.
Thanks,
Ninad

**Comment by hjiang36** [comment]
Hi Ninad,

The sensor is scanning at 10Hz per second. You can set the sdk to output frames that accumulating all points within a second by specifying proper 'options' when calling 'initialize'. But that could make moving objects pretty blurry.

Let us know if you need some further explanation.

**Comment by jadhavhninad** [comment]
Hi Jiang,
I tried to change the frame options and it seems that the duration gets updated but , the mode does not change at all. I have made the following changes in the cepton_export.py file.

``

    options = {}
    frame_options = {}
    frame_options["mode"] = 1
    frame_options["length"] = 10

    if args.capture_path is not None:
        options["capture_path"] = fix_path(args.capture_path)
    cepton_sdk.initialize(**options)
    cepton_sdk.set_frame_options(**frame_options)
    print(cepton_sdk.get_frame_length())
    print(cepton_sdk.get_frame_mode())

``

The output is - 
10.0
FrameMode.STREAMING


Am I doing it correctly?

**Comment by hjiang36** [comment]
Thanks for the code snippet.
I just checked the code and seems like there is some issue in cepton_sdk.set_frame_options and the mode is not properly used in that function. We will get this fixed in the next release.

Before that, you can use c_set_frame_options to set the mode and length as a workaround.

```
c_options = cepton_sdk.c.c_create_frame_options()
c_options.mode = 1
c_options.length = 0.5
cepton_sdk.c.c_set_frame_options(c_options)

```
