### ISSUE TITLE
`capture.hpp` is using headers form wrong location

### ISSUE THREAD

**Issue by t0ny-peng** [ceptontech/cepton_sdk_redist#6]
`capture.cpp` includes `cepton_sdk/capture.hpp`. However, the file is actually under `src/` so compiler fails to find it. 

Our current workaround is to copy the header file to a folder called `cepton_sdk` but it's kinda dirty hack. Do you have any plan fixing this? Thanks.

**Comment by spectralflight** [comment]
The capture code and samples are meant for reference only. They are not meant to be complete code, but rather templates. Most users should use the capture methods in the SDK API.
