### ISSUE TITLE
What version of asio does the sdk use?

### ISSUE THREAD

**Issue by cho3** [ceptontech/cepton_sdk_redist#8]
We are running into some mysterious segfaults on shutdown on applications linked against the `cepton_sdk`.

From what it looks like, a different set of classes which use ASIO ends up calling the destructor baked into the `cepton_sdk` library.

We are using cepton_sdk 1.13, and our other library is using [ASIO v1.12.2](https://github.com/chriskohlhoff/asio/tree/22afb86087a77037cd296d27134756c9b0d2cb75/asio/include)

**Comment by spectralflight** [comment]
That is odd. Could you try using the latest SDK 1.16.0 and see if it fixes the issue? We are using ASIO v1.13.0. It is statically linked though, so I don't see how there could be a conflict.

- Are you on Windows?
- Are you statically or dynamically linking the SDK?
- Are you sure that `cepton_sdk_deinitialize` is being called?

**Comment by cho3** [comment]
@spectralflight Thanks for the response (and sorry for causing issues).

I'll give 1.16 a try, but as for your other questions:

> Are you on Windows?

No, we're using a docker image of Ubuntu 18.04 LTS on a Ubuntu 16.04 LTS host

> Are you statically or dynamically linking the SDK?

I tried both, and I get the same issue both ways (side note, I also tried shuffling the linking order in both cases--didn't help). By default we dynamically link.

> Are you sure that cepton_sdk_deinitialize is being called?

It wasn't (doh!), but I still see the same issue after adding it in.

**Comment by spectralflight** [comment]
Well...your answers invalidated all of my ideas lol. Failing to call cepton_sdk_deinitialize is the most common cause of segfaults.

Do you get the same issue on a normal machine (not inside a docker image)? 

If 1.16 doesn't fix the issue, then I can try linking a different version of ASIO for you to see if that helps.

**Comment by spectralflight** [comment]
Is this issue resolved? If so, I would like to close the issue.
