### ISSUE TITLE
'sample_lidar_replay' dosn't work on Drive AGX

### ISSUE THREAD

**Issue by MoriYu0011** [ceptontech/cepton_sdk_redist#9]
By using Vista P60, a command 'sample_lidar_replay' dosn't work on Drive AGX.
I already set such settings below:
```
sudo ifconfig [if_name] 192.168.0.11 netmask 255.255.0.0
sudo ./sample_lidar_replay --protocol=lidar.socket --params=device=CUSTOM,ip=192.168.68.152,port=8808,decoder=/home/nvidia/tmp/libcepton_driveworks.so,scan-frequency=10,protocol=udp
```
The 'libcepton_driveworks.so' was successfully built on the AGX.

I hope that this command can replay the lidar data in real-time. However, 
* A viewer of LiDAR was opened for an instant, but the viewer suddenly closed because of 'Segmentation fault'.
* There is no other error messages when 'Segmentation fault' is occurred.

Could you show me any ideas to solve this problem?
Thanks.

**Comment by spectralflight** [comment]
Unfortunately, we don't have access to a Drive AGX unit, so we have no way to test the driver. The Driveworks driver is meant as reference code only. I just updated the README to clarify this.
